export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const UPDATE_CUST_SUCCESS = "UPDATE_CUST_SUCCESS";
export const UPDATE_CUST_ADD_SUCCESS = "UPDATE_CUST_ADD_SUCCESS";
