export const FETCH_REST_REQUEST = 'FETCH_REST_REQUEST';
export const FETCH_REST_FAILURE = 'FETCH_REST_FAILURE';
export const FETCH_REST_SUCCESS = 'FETCH_REST_SUCCESS';
export const UPDATE_REST_SUCCESS = 'UPDATE_REST_SUCCESS';
