export const FETCH_RESTSIGNUP_REQUEST = 'FETCH_RESTSIGNUP_REQUEST';
export const FETCH_RESTSIGNUP_SUCCESS = 'FETCH_RESTSIGNUP_SUCCESS';
export const FETCH_RESTSIGNUP_FAILURE = 'FETCH_RESTSIGNUP_FAILURE';
