export const FETCH_RESTLOGIN_REQUEST = 'FETCH_RESTLOGIN_REQUEST';
export const FETCH_RESTLOGIN_SUCCESS = 'FETCH_RESTLOGIN_SUCCESS';
export const FETCH_RESTLOGIN_FAILURE = 'FETCH_RESTLOGIN_FAILURE';

