export const FETCH_FAVOURITE_REQUEST = 'FETCH_FAVOURITE_REQUEST';
export const FETCH_FAVOURITE_FAILURE = 'FETCH_FAVOURITE_FAILURE';
export const FETCH_FAVOURITE_SUCCESS = 'FETCH_FAVOURITE_SUCCESS';
export const ADD_FAVOURITE_SUCCESS = 'ADD_FAVOURITE_SUCCESS';
export const DEL_FAVOURITE_SUCCESS = 'DEL_FAVOURITE_SUCCESS';

