export const FETCH_RESTAURANTS_REQUEST = 'FETCH_RESTAURANTS_REQUEST';
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
export const FETCH_RESTAURANTS_FAILURE = 'FETCH_RESTAURANTS_FAILURE';

export const ONLY_PICKUP = 'ONLY_PICKUP';
export const ONLY_DELIVERY = 'ONLY_DELIVERY';
export const ADD_SEARCH_TEXT = 'ADD_SEARCH_TEXT';


export const GET_RESTID_FROM_DISH = 'GET_RESTID_FROM_DISH'
export const GET_RESTID_FROM_TYPE = 'GET_RESTID_FROM_TYPE'




// export const FILTER_RESTAURANTS_DELIVERY = 'FETCH_RESTAURANTS_DELIVERY';
// export const FILTER_RESTAURANTS_PICKUP = 'FETCH_RESTAURANTS_PICKUP';



